blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

name: object

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('post/<slug:slug>/', views.PostDV.as_view(), name='post_detail'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    path('search/', views.SearchFormView.as_view(), name='search'),
    path('add/', views.PostCreateView.as_view(), name='add',),
    path('change/', views.PostChangeLV.as_view(), name='change',),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update',),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete',),
]

community/urls.py
from django.urls import path
from community import views

app_name = 'community'

urlpatterns = [
    path('', views.CommunityLV.as_view(), name='index'),
    path('<int:pk>/', views.CommunityDV.as_view(), name='detail'),
    path('add/', views.CommunityCreateView.as_view(), name='add', ),
    path('change/', views.CommunityChangeLV.as_view(), name='change', ),
    path('<int:pk>/update/', views.CommunityUpdateView.as_view(), name='update', ),
    path('<int:pk>/delete/', views.CommunityDeleteView.as_view(), name='delete', ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config.views import HomeView
from config.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('', HomeView.as_view(), name='home'),
    path('community/', include('community.urls')),
    path('blog/', include('blog.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=divice-width, initial-scale=1">
    <title>{% block title %}한신대 커뮤니티{% endblock %} </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">WebProgramming Final Project</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item mx-1 btn btn-primary">
            <a class="nav-link text-white" href="{% url 'home' %}">홈</a></li>
        <li class="nav-item mx-1 btn btn-primary">
             <a class="nav-link text-white" href="{% url 'community:index' %}">HOT게시판</a></li>
        <li class="nav-item mx-1 btn btn-primary">
            <a class="nav-link text-white" href="{% url 'blog:index' %}">자유게시판</a>

        <li class="nav-item dropdown mx-1 btn btn-primary">
            <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">메뉴</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'blog:add' %}">글쓰기</a>
                <a class="dropdown-item" href="{% url 'blog:change' %}">글수정</a>
            </div>
        </li>

        <li class="nav-item dropdown mx-1 btn btn-primary">
            <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">ETC</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'admin:index' %}">관리자</a>
                <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'blog:search' %}">검색</a>
            </div>
        </li>
    </ul>
      <!--
    <form class="form-inline my-2" action="" method="post">{% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
    </form>
        -->
      <ul class="navbar-nav ml-5 mr-5">
          <li class="nav-item dropdown mx-1 btn btn-primary">
              {% if user.is_active %}
              <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                  <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
              <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
                  <a class="dropdown-item" href="{% url 'password_change' %}">비밀번호 변경하기</a>
              </div>
              {% else %}
              <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                  <i class="fas fa-user"></i>&ensp;마이페이지&ensp;</a>
              <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'login' %}">로그인하기</a>
                  <a class="dropdown-item" href="{% url 'register' %}">회원가입하기</a>
              </div>
              {% endif %}
          </li>
      </ul>
  </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/ed70e405c3.js" crossorigin="anonymous"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
  .home-image{
  background-image: url("{% static 'img/hansin1.jpg' %}");
  background-repeat: no-repeat;
  background-position: center;
  background-size: 100%;
  height: 500px;
  border-top: 10px solid #ccc;
  border-bottom: 10px solid #ccc;
  padding: 20px 0 0 20px;
  }
  .title{
  color: #000;
  font-weight: bold;
  }
  .powered{
  position: relative;
  top: 77%;
  color: #000;
  font-style: italic;
  }
</style>
{% endblock %}

{% block content %}
  <div class="home-image">
    <h2 class="title">Hansin Univ Commnunity</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i>한신대학교의 모든 정보는 이곳에! 한신대 커뮤니티! </h4>
  </div>

  <hr style="margin: 10px 0;">

  <div class="row text-center">
    <div class="col-sm-6">
      <h3>HOT게시판</h3>
        <p>커뮤니티에서 오늘 하루 가장 인기있는 포스트를 모아! 모아!</p>
    </div>
   <div class="col-sm-6">
     <h3>자유게시판</h3>
     <p>당신의 생각을 마음껏 적어주세요!</p>
   </div>
  </div>

{%  endblock content%}

{% block footer %}

<footer class="fixed-bottom bg-info">
  <div class="text-white font-italic text-right mr-5">made by social_201527014_ryu_myunggi</div>
</footer>
{% endblock %}